---
title: "R Notebook"
output: html_document
---

The [R plugin](https://www.jetbrains.com/help/pycharm/r-plugin-support.html) for IntelliJ-based IDEs provides
handy capabilities to work with the [R Markdown](https://www.jetbrains.com/help/pycharm/r-markdown.html) files.
To [add](https://www.jetbrains.com/help/pycharm/r-markdown.html#add-code-chunk) a new R chunk,
```{r}
library(jsonlite)
library(sfarrow)
```


```{r}
#LIST = st_read_parquet("LI_ETL/data/large_data/LIST_v0-5.parquet")
LIST_sample = st_read_parquet("LI_ETL/data/large_data/LIST_sample.parquet")
```




```{r}
json_string <- '[{"persname": {"name": [{"@type": "praenomen", "#text": "C."}, {"@type": "nomen", "#text": "Iulius"}, {"@type": "cognomen", "#text": "Capito*"}]}, "@sex": "M", "@{http://www.w3.org/XML/1998/namespace}id": "HD057920_1"}, {"persname": {"name": [{"@type": "praenomen", "#text": "C."}, {"@type": "nomen", "#text": "Iulius"}, {"@type": "cognomen", "#text": "Maximus+"}]}, "@sex": "M", "@{http://www.w3.org/XML/1998/namespace}id": "HD057920_2"}]'

```

Type any R code in the chunk, for example:
```{r}
parsed_json <- fromJSON(json_string)
```
```{r}

```